version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
     - dbdata:/var/lib/postgresql/data
    env_file: ./searching-front/.env.local #Here we are using the already existing .env.local file
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch:8.4.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"

    ports:
      - 9200:9200
  # proxy:
  #   platform: linux/x86_64
  #   build: ./proxy
  #   volumes: 
  #     - ./proxy:/app
  front:
    container_name: front
    build: ./searching-front
    restart: always
    ports:
      - 80:3000
  watcher:
    container_name: watcher
    depends_on:
      - elasticsearch
    build: 
      context: ./searching-front
      dockerfile: Dockerfile.watcher
    restart: always

networks:
  es-net:
    driver: bridge

volumes:
 dbdata:
